### ISSUE TITLE
A suggestion to use a callback instead of the while loop

### ISSUE THREAD

**Issue by 10git** [bjarne-hansen/py-nrf24#19]
Dear Bjarne,

In your example I noticed that little while loop that constantly checks for available data. Although it works, it pushes the CPU to an unnecessary load. Moreover it happens to have few messages circulating through the NRF24. The good thing is that you can change this behavior with a callback approach. The advantage is that the callback will only be called when data arrives, so it lets the CPU take care of some other tasks.

To implement it, the NRF24 class will need a new attribute, the callback itself. The callback can be set by passing it to the constructor:

```
self.cb = cb
```

Then, inside the constructor you set the callback to be called on the falling edge of the MOSI pin. This can be achieved with the pigpio library:
```
pi.callback(10, pigpio.FALLING_EDGE, self.callback)
```
Then the callback:

```
def callback(this, a=None, b=None, c=None):
	if self.data_ready():
		self.cb(self.get_payload())
```

That’s all. Please let me know if you find it usefull and if it deserves to be perpetuated.

Regards,
Alinux.

**Comment by Lennart99** [comment]
Dear  Alinus,
I got notified about your issue because I have an open PR myself unrelated to your issue 

Your idea of checking the MOSI pin won't work because the data is not sent from the NRF to the raspberry pi until the pi asks for the data. The NRF has an interupt pin for these kinds of purposes. 

Then this: how would you check for any pin before calling the callback without making a loop yourself? I don't think the pigpio library supports interupts.

If your solution would be to make a loop in the library to check for updates, I don't really see any advantages of this functionality.

**Comment by bjarne-hansen** [comment]
I think this sort of change would require another deep dive in the NRF24L01 technical specification to see what options are in reality provided by the module.  I have not seen a specific "data ready" event (interrupt).

When time permits I will run through the specification and look for it.  I will keep this issue open as an "enhancement".

//bjarne

**Comment by 10git** [comment]
I agree for the deep dive, the intent was to expose an idea to start with. If the MOSI pin goes low for many reasons, one of them can be a sign that new data is available. When the MOSI goes low, test that self.data_ready(). If the condition is true, then the data is here, and can be retrieved with self.get_payload(). Hence, your code sample from README.md can be rewritten as follows (it worked successfully, with the instructions given in the initial suggestion):
```
import pigpio, time, struct
from nrf24 import NRF24, RF24_PAYLOAD, RF24_RX_ADDR
def cb(payload=None):
    (p, t, h) = struct.unpack('<Bff', payload)
    print('Temperature: {}, humidity: {}'.format(t, h))
pi = pigpio.pi('localhost')
radio = NRF24(pi, ce=25, payload_size=RF24_PAYLOAD.DYNAMIC, cb=cb)
radio.open_reading_pipe(RF24_RX_ADDR.P1, [0x01, 0xCE, 0xFA, 0xBE, 0xBA])
while True: time.sleep(999999) # go to sleep
``` 
Regards,
Alinux

**Comment by Lennart99** [comment]
How would the MOSI pin go low ehen data is received?
MOSI stands for Master Out Slave In
This means is is the output of the RPI to the NRF24

**Comment by bjarne-hansen** [comment]
Dear @10git and @Lennart99 
 
I had a quick look at the specification (attached).  I tend to agree with @Lennart99 that the MISO PIN is not the way to go.  As far as I can see, that PIN is triggered by the master sending a command to the slave asking for data (disclaimer - it was a very quick look).

However, I see that there is an IRQ that is triggered on TX_DS (data sent) and RX_DR (data ready).

As you can see on the following PIN out of a module, the IRQ pin is avalable.
![nRF24L01-Pinout](https://user-images.githubusercontent.com/10808404/96678059-336dd400-1371-11eb-961b-f4c3421bb782.png)

This PIN may be used to detect TX/RX IRQ - I have not tried it yet.

Now, on an Arduino or raw Atmega328 IC this could easily be attached to the Atmega IRQ PIN and if it is triggered the interrupt handler would run.  Now, the interrupt handler on the Atmega is normally just used to set a flag, so that the main loop of the Atmega would be able to see that data is available.

On the Raspberry, this would require some sort of interrupt handling that is not just introducing a busy loop elsewhere.  I have found this article that shows different approaches, including one that seems to have a callback based on pigpio.

https://roboticsbackend.com/raspberry-pi-gpio-interrupts-tutorial/

I have not tried it - but I think it would be worth a try.  Again, using this approach would not require any changes to the py-nrf24 library as you can implement the interrupt handler outside the library for signalling data is available, and then call the library functions to retrieve it.

I will get back when I find the time to a little experiment.  Feel free to try the approach in the article above in until then.

//bjarne

[
[nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf](https://github.com/bjarne-hansen/py-nrf24/files/5413492/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf)
](url)

**Comment by Lennart99** [comment]
I have done some additional research:

- The IRQ pin on the is active low, which means we the callback should react to falling edge transactions
- The IRQ pin reacts to three interrupt sources: Received data ready(RX_DR), data sent (TX_DS) and maximum number of retransmits (MAX_RT). these interrupts can be masked using the CONFIG register, making it possible to disable unneeded interrupts
- About the handling of the RX_DR interrupt, the datasheets says the following procedure should be followed:
	1: Read payload through SPI 
	2: Clear RX_DR in status register 
	3: Read FIFO_STATUS to check if there are more payloads available in the RX FIFO 
	4: If there is more data available, repeat from step 1
This will then 

Additionally, there is a callback function available in the pigpio library: http://abyz.me.uk/rpi/pigpio/python.html#callback

I have tested this function with a push button but haven't tested it yet using the NRF24
```import time

import pigpio

def cbf(gpio, level, tick):
    print(level)

pi = pigpio.pi()
pi.set_mode( 26, pigpio.INPUT)
cb1 = pi.callback(26, pigpio.EITHER_EDGE, cbf)

# sleep to prevent the program from stopping
while True:
    time.sleep(1)
```

I might try to integrate this into the library in a few weeks when I have more time if you are interested

**Comment by bjarne-hansen** [comment]
Status Update:

Easter gave me the opportunity to look into this, and I have managed to test code similar to the one provided by @Lennart99 above.  It works perfectly using code like that sketched by @Lennart99 above using FALLING_EDGE.

Basically, the callback will just have to perform the check to see if data is available, and fetch the payload - or check if package was sent successfully in case of a send operation (packages lost, retries).

I am plannning a 2.0.0 release in a short while and will include examples of IRQ callbacks for both send and receive scenarios.  The 2.0.0 release will include a nummer of other significant changes.

I will close this issue and hope you will enjoy the 2.0.0 release.
