### ISSUE TITLE
Use of library on jetson nano

### ISSUE THREAD

**Issue by janezlapajne** [bjarne-hansen/py-nrf24#36]
Hello, I successfully established communication between two RP-s as described in the readme. Can library also be used for jetson nano, because the command **sudo apt-get install python-pigpio python3-pigpio** throws me and error: E: Unable to locate package python3-pigpio? Download using pip installs pigpio library, but the deamon still won't start.

**Comment by bjarne-hansen** [comment]
Hi

The raspberry pi uses an ARM processor like The jetson nano, so I would guess that it is possible.

However, since the raspberry and jetson CPUs are different models, a jetson specific build may be needed.

A pigpio distribution is obviously not in the package manager for the jetson as you have already observed.

This means that you will have to build the jetson version from source.

Source of pigpiod
https://github.com/joan2937/pigpio

The pynrf24 does not need any platform specific build as it is just python.

Good luck with building on the jetson.

//bjarne

**Comment by janezlapajne** [comment]
Thank you for your quick answer! I will try what you have suggested and will see if it works 👨

**Comment by janezlapajne** [comment]
@bjarne-hansen I tried to build pigpio from source, but unfortunately without any luck. Is it possible to quickly modify this library in a way that it wouldn't be dependent on pigpio deamon?

**Comment by bjarne-hansen** [comment]
Easy is a relative term ;-) but I believe the GPIO are available through RPi.GPIO.

import RPi.GPIO

That said, I believe this is quite low-level access to the pins, so a better approach would be to use spidev.

import spidev

See https://learn.sparkfun.com/tutorials/python-programming-tutorial-getting-started-with-the-raspberry-pi/experiment-3-spi-and-analog-input

Using spidev for SPI communication can establish an alternative to the pigpiod daemon.

Feel free to clone the project and give it a go. 

Please let me know if you are successful (or if you have additional questions).

//bjarne

**Comment by bjarne-hansen** [comment]
Also, please see https://www.sparkfun.com/datasheets/Components/SMD/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf

In chapter 8 is the command reference, and it should be relatively easy to identify where and how the commands are used in the existing code.

**Comment by janezlapajne** [comment]
Thank you for all the references. I will look into it.
